#!/bin/sh
# mk/embed-clp.sh OUTPUT RULE.clp [RULE.clp ...]
#
# Generate a C translation unit embedding each rule file as a byte
# array, plus the load-order table declared in fd_internal.h (struct
# fd_embedded_rule). Argument order IS load order — pass the files in
# the same canonical sequence fd_create loads from disk. Bytes are
# emitted as hex (via od) rather than a string literal, so no escaping
# rules apply and the file content round-trips exactly.
set -eu

out="$1"
shift

{
	printf '/* Generated by mk/embed-clp.sh -- do not edit. */\n'
	printf '#include "fd_internal.h"\n\n'
	i=0
	for f in "$@"; do
		printf 'static const unsigned char rule_%d[] = {\n' "$i"
		od -An -v -tx1 "$f" |
		    awk '{ for (n = 1; n <= NF; n++) printf "0x%s,", $n; print "" }'
		printf '};\n\n'
		i=$((i + 1))
	done
	printf 'const struct fd_embedded_rule fd_embedded_rules[] = {\n'
	i=0
	for f in "$@"; do
		base=${f##*/}
		size=$(($(wc -c < "$f")))
		printf '\t{ "%s", rule_%d, %d },\n' "$base" "$i" "$size"
		i=$((i + 1))
	done
	printf '};\n\n'
	printf 'const size_t fd_embedded_rules_count =\n'
	printf '    sizeof fd_embedded_rules / sizeof fd_embedded_rules[0];\n'
} > "$out"
